const data = [
  '10000 Maniacs',
  '10cc',
  '112',
  '112 Featuring Foxy Brown',
  '112 Featuring Lil Zane',
  '112 Featuring The Notorious Big And Mase',
  '1910 Fruitgum Company',
  '2 Chainz',
  '2 Chainz Featuring Drake',
  '2 Pistols Featuring Tpain And Tay Dizm',
  '20 Fingers Featuring Gillette',
  '2pac',
  '2pac Featuring Eric Williams',
  '3 Doors Down',
  '38 Special',
  '3lw',
  '3oh3',
  '3oh3 Featuring Keha',
  '3t',
  '4 Non Blondes',
  '4 00 Pm',
  '5 Seconds Of Summer',
  '50 Cent',
  '50 Cent Featuring Justin Timberlake And Timbaland',
  '50 Cent Featuring Mobb Deep',
  '50 Cent Featuring Nate Dogg',
  '50 Cent Featuring Olivia',
  '69 Boyz',
  '702',
  '95 South',
  '98 Degrees',
  'A Flock Of Seagulls',
  'A Great Big World And Christina Aguilera',
  'A Taste Of Honey',
  'Aaliyah',
  'Aaron Hall',
  'Aaron Neville',
  'Abba',
  'Abc',
  'Ace',
  'Ace Frehley',
  'Ace Hood Featuring Future And Rick Ross',
  'Ace Of Base',
  'Adam Clayton And Larry Mullen',
  'Adam Lambert',
  'Adele',
  'Adina Howard',
  'Aerosmith',
  'After 7',
  'After The Fire',
  'Aha',
  'Ahmad',
  'Air Supply',
  'Akon',
  'Akon Featuring Colby Odonis And Kardinal Offishall',
  'Akon Featuring Eminem',
  'Akon Featuring Snoop Dogg',
  'Akon Featuring Styles P',
  'Al B Sure',
  'Al Green',
  'Al Stewart',
  'Al Wilson',
  'Alabama',
  'Alabama And N Sync',
  'Alan Jackson',
  'Alan Jackson Featuring Jimmy Buffett',
  'Alan Oday',
  'Alanis Morissette',
  'Alannah Myles',
  'Albert Hammond',
  'Alessia Cara',
  'Alex Clare',
  'Alice Cooper',
  'Alice Deejay',
  'Alicia Bridges',
  'Alicia Keys',
  'Alicia Keys Featuring Tony Toni Tone',
  'Alive N Kickin',
  'All Saints',
  'Allure Featuring 112',
  'Aloe Blacc',
  'Amanda Perez',
  'Amazing Rhythm Aces',
  'Amber',
  'Ambrosia',
  'Ame Lorain',
  'America',
  'American Authors',
  'Amerie',
  'Amii Stewart',
  'Amy Grant',
  'Amy Winehouse',
  'Andrea True Connection',
  'Andrew Gold',
  'Andy Gibb',
  'Andy Grammer',
  'Andy Kim',
  'Andy Williams',
  'Angie Martinez Featuring Lil Mo And Sacario',
  'Animotion',
  'Anita Baker',
  'Anita Ward',
  'Ann Wilson And Robin Zander',
  'Anna Kendrick',
  'Anne Murray',
  'Annie Lennox',
  'Another Bad Creation',
  'Aqua',
  'Arcadia',
  'Archie Bell The Drells',
  'Aretha Franklin',
  'Aretha Franklin And George Michael',
  'Argent',
  'Ariana Grande',
  'Ariana Grande And The Weeknd',
  'Ariana Grande Featuring Iggy Azalea',
  'Ariana Grande Featuring Mac Miller',
  'Ariana Grande Featuring Zedd',
  'Arlo Guthrie',
  'Arrested Development',
  'Arthur Conley',
  'Asap Rocky Featuring Drake 2 Chainz And Kendrick Lamar',
  'Ashanti',
  'Asher Roth',
  'Ashford Simpson',
  'Ashlee Simpson',
  'Asia',
  'Atlanta Rhythm Section',
  'Atlantic Starr',
  'Audioslave',
  'Avant',
  'Avant Featuring Snoop Dogg',
  'Average White Band',
  'Avicii',
  'Avril Lavigne',
  'Awolnation',
  'Az',
  'Az Yet',
  'Az Yet Featuring Peter Cetera',
  'B2k',
  'B2k And P Diddy',
  'Baauer',
  'Baby Bash Featuring Akon',
  'Baby Bash Featuring Frankie J',
  'Baby Bash Featuring Tpain',
  'Baby Boy Da Prince',
  'Babyface',
  'Backstreet Boys',
  'Bad Company',
  'Bad English',
  'Bad Meets Evil Featuring Bruno Mars',
  'Badfinger',
  'Baltimora',
  'Bananarama',
  'Barbara Lewis',
  'Barbara Mason',
  'Barbra Streisand',
  'Barbra Streisand Barry Gibb',
  'Barbra Streisand Donna Summer',
  'Barbra Streisand And Bryan Adams',
  'Barenaked Ladies',
  'Barry Manilow',
  'Barry Mcguire',
  'Barry White',
  'Bastille',
  'Bay City Rollers',
  'Bb King',
  'Bbmak',
  'Beastie Boys',
  'Beck',
  'Becky G',
  'Bee Gees',
  'Beenie Man',
  'Belinda Carlisle',
  'Bell Biv Devoe',
  'Ben E King',
  'Benny Mardones',
  'Berlin',
  'Bert Kaempfert',
  'Bertie Higgins',
  'Bette Midler',
  'Better Than Ezra',
  'Betty Wright',
  'Beverly Bremers',
  'Beyonce',
  'Beyonce Featuring Jay Z',
  'Beyonce Featuring Jayz',
  'Beyonce Featuring Sean Paul',
  'Beyonce Featuring Shakira',
  'Beyonce Featuring Slim Thug',
  'Big Brother And The Holding Company',
  'Big Mountain',
  'Big Pun Featuring Joe',
  'Big Sean Featuring Chris Brown',
  'Big Sean Featuring Drake',
  'Big Sean Featuring E40',
  'Big Sean Featuring Nicki Minaj',
  'Big Tymers',
  'Bill Medley And Jennifer Warnes',
  'Bill Withers',
  'Billie Myers',
  'Billy Currington',
  'Billy Idol',
  'Billy Joe Royal',
  'Billy Joel',
  'Billy Ocean',
  'Billy Paul',
  'Billy Preston',
  'Billy Preston And Syreeta',
  'Billy Ray Cyrus',
  'Billy Squier',
  'Billy Swan',
  'Biz Markie',
  'Bj Thomas',
  'Black Box',
  'Blackstreet',
  'Blackstreet Featuring Dr Dre',
  'Blackstreet Featuring M Ya Mase And Blinky Blink',
  'Blake Shelton',
  'Blake Shelton Featuring Pistol Annies And Friends',
  'Blaque',
  'Blessid Union Of Souls',
  'Blink 182',
  'Blondie',
  'Blood Sweat Tears',
  'Bloodstone',
  'Blu Cantrell',
  'Blue Cheer',
  'Blue Magic',
  'Blue October',
  'Blue Ridge Rangers',
  'Blue Swede',
  'Blues Image',
  'Blues Magoos',
  'Blues Traveler',
  'Bob',
  'Bob Dylan',
  'Bob Featuring Bruno Mars',
  'Bob Featuring Hayley Williams',
  'Bob Featuring Rivers Cuomo',
  'Bob Lind',
  'Bob Seger',
  'Bob Seger The Silver Bullet Band',
  'Bob Seger And The Silver Bullet Band',
  'Bob Seger System',
  'Bob Welch',
  'Bobbi Martin',
  'Bobbie Gentry',
  'Bobby Boris Pickett And The Cryptkickers',
  'Bobby Brown',
  'Bobby Caldwell',
  'Bobby Darin',
  'Bobby Fuller Four',
  'Bobby Goldsboro',
  'Bobby Hebb',
  'Bobby Mcferrin',
  'Bobby Sherman',
  'Bobby Shmurda',
  'Bobby Valentino',
  'Bobby Vee',
  'Bobby Vinton',
  'Bobby Womack',
  'Bodeans',
  'Bon Jovi',
  'Bon Jovi Featuring Jennifer Nettles',
  'Bonnie Pointer',
  'Bonnie Raitt',
  'Bonnie Tyler',
  'Boston',
  'Bow Wow Featuring Chris Brown And Johnt A Austin',
  'Bow Wow Featuring Ciara',
  'Bow Wow Featuring Omarion',
  'Bow Wow Featuring Tpain And Johnt A Austin',
  'Boy Krazy',
  'Boy Meets Girl',
  'Boys Club',
  'Boys Like Girls',
  'Boys Like Girls Featuring Taylor Swift',
  'Boyz Ii Men',
  'Boz Scaggs',
  'Brad Paisley',
  'Brad Paisley And Carrie Underwood',
  'Brandy',
  'Brandy And Monica',
  'Brandy Featuring Wanya Morris',
  'Brantley Gilbert',
  'Bread',
  'Breakfast Club',
  'Breathe',
  'Brenda K Starr',
  'Brenda Lee',
  'Brenda Russell Featuring Joe Esposito',
  'Brenton Wood',
  'Brewer Shipley',
  'Brian Mcknight',
  'Brian Mcknight Featuring Mase',
  'Brick',
  'Britney Spears',
  'Brook Benton',
  'Brooke Valentine Featuring Lil Jon And Big Boi',
  'Brooks Dunn',
  'Brownstone',
  'Brownsville Station',
  'Bruce Hornsby And The Range',
  'Bruce Springsteen',
  'Bruce Willis',
  'Bruno Mars',
  'Bryan Adams',
  'Bryan Adams Rod Stewart And Sting',
  'Bt Express',
  'Bubba Sparxxx Featuring Ying Yang Twins',
  'Buckcherry',
  'Buffalo Springfield',
  'Burton Cummings',
  'Busta Rhymes',
  'Busta Rhymes And Mariah Carey Featuring Flipmode Squad',
  'Busta Rhymes Featuring Janet',
  'Busta Rhymes Featuring P Diddy And Pharrell',
  'Bw Stevenson',
  'C W Mccall',
  'Cah Out',
  'Cali Swag District',
  'Calloway',
  'Calvin Harris',
  'Calvin Harris And Disciples',
  'Calvin Harris Featuring Ellie Goulding',
  'Calvin Harris Featuring Florence Welch',
  'Calvin Harris Featuring Neyo',
  'Cameo',
  'Camron Featuring Juelz Santana',
  'Camron Featuring Juelz Santana And Freekey Zekey',
  'Candi Staton',
  'Candlebox',
  'Capital Cities',
  'Captain Tennille',
  'Captain Hollywood Project',
  'Carl Douglas',
  'Carl Thomas',
  'Carla Thomas',
  'Carly Rae Jepsen',
  'Carly Simon',
  'Carly Simon James Taylor',
  'Carol Douglas',
  'Carole King',
  'Carrie Underwood',
  'Cascada',
  'Case',
  'Case Featuring Foxy Brown',
  'Case Featuring Joe',
  'Cassidy Featuring R Kelly',
  'Cassie',
  'Cat Stevens',
  'Cathy Dennis',
  'Cc Music Factory',
  'Cece Peniston',
  'Cee Lo Green',
  'Celine Dion',
  'Celine Dion And Peabo Bryson',
  'Chad Brock',
  'Chad Kroeger Featuring Josey Scott',
  'Chairmen Of The Board',
  'Chaka Khan',
  'Chamillionaire Featuring Krayzie Bone',
  'Champaign',
  'Changing Faces',
  'Chante Moore',
  'Charlene',
  'Charles Eddie',
  'Charles Wright The Watts 103rd Street Rhythm Band',
  'Charley Pride',
  'Charli Xcx',
  'Charlie Daniels Band',
  'Charlie Dore',
  'Charlie Puth Featuring Meghan Trainor',
  'Charlie Rich',
  'Cheap Trick',
  'Checkmates Ltd',
  'Cher',
  'Cher And Peter Cetera',
  'Cher Lloyd',
  'Cherish Featuring Sean P',
  'Cheryl Lynn',
  'Chesney Hawkes',
  'Chic',
  'Chicago',
  'Chingy',
  'Chingy Featuring Jweav',
  'Chingy Featuring Ludacris And Snoop Dogg',
  'Chingy Featuring Tyrese',
  'Chris Brown',
  'Chris Brown And Tyga',
  'Chris Brown Featuring Juelz Santana',
  'Chris Brown Featuring Lil Wayne',
  'Chris Brown Featuring Lil Wayne And Busta Rhymes',
  'Chris Brown Featuring Lil Wayne And French Montana Too Short Or Tyga',
  'Chris Brown Featuring Tpain',
  'Chris Brown Featuring Tyga And Kevin Mccall',
  'Chris Brown Featuring Usher And Rick Ross',
  'Chris De Burgh',
  'Chris Isaak',
  'Chris Montez',
  'Christie',
  'Christina Aguilera',
  'Christina Aguilera Featuring Lil Kim',
  'Christina Milian',
  'Christina Perri',
  'Christine Mcvie',
  'Christopher Cross',
  'Chumbawamba',
  'Ciara',
  'Ciara And Missy Elliott',
  'Ciara Featuring Chamillionaire',
  'Ciara Featuring Ludacris',
  'Ciara Featuring Petey Pablo',
  'Citizen King',
  'City High',
  'City High Featuring Eve',
  'Clarence Carter',
  'Classics Iv',
  'Clay Aiken',
  'Clean Bandit Featuring Jess Glynne',
  'Cliff Richard',
  'Climax',
  'Climax Blues Band',
  'Clint Holmes',
  'Club Nouveau',
  'Cobra Starship Featuring Leighton Meester',
  'Cobra Starship Featuring Sabi',
  'Colbie Caillat',
  'Colby Odonis Featuring Akon',
  'Coldplay',
  'Collective Soul',
  'Color Me Badd',
  'Commander Cody And His Lost Planet Airmen',
  'Commodores',
  'Coolio',
  'Coolio Featuring 40 Thevz',
  'Coolio Featuring Lv',
  'Corey Hart',
  'Corina',
  'Cornelius Brothers Sister Rose',
  'Corona',
  'Count Five',
  'Craig David',
  'Craig Mack',
  'Crash Test Dummies',
  'Crazy Elephant',
  'Crazy Town',
  'Cream',
  'Creed',
  'Creedence Clearwater Revival',
  'Crime Mob And Lil Scrappy',
  'Crispian St Peters',
  'Crosby Stills Nash',
  'Crosby Stills Nash Young',
  'Crowded House',
  'Crucial Conflict',
  'Crystal Gayle',
  'Crystal Waters',
  'Culture Beat',
  'Culture Club',
  'Curtis Mayfield',
  'Cutting Crew',
  'Cyndi Lauper',
  'Cypress Hill',
  'D12',
  'D4l',
  'Da Brat',
  'Da Brat Featuring Tyrese',
  'Daddy Yankee',
  'Daft Punk Featuring Pharrell Williams',
  'Damn Yankees',
  'Dan Fogelberg',
  'Dan Hartman',
  'Dan Hill',
  'Dan Hill Featuring Vonda Shepard',
  'Dangelo',
  'Daniel Bedingfield',
  'Daniel Boone',
  'Daniel Powter',
  'Danity Kane',
  'Danity Kane Featuring Yung Joc',
  'Darius Rucker',
  'Darryl Worley',
  'Daryl Hall',
  'Daryl Hall John Oates',
  'Das Efx',
  'Daughtry',
  'Dave Edmunds',
  'Dave Loggins',
  'Dave Matthews Band',
  'David Archuleta',
  'David Banner',
  'David Banner Featuring Chris Brown',
  'David Bowie',
  'David Cook',
  'David Essex',
  'David Gates',
  'David Guetta Featuring Akon',
  'David Guetta Featuring Flo Rida And Nicki Minaj',
  'David Guetta Featuring Nicki Minaj',
  'David Guetta Featuring Nicki Minaj Bebe Rexha And Afrojack',
  'David Guetta Featuring Sia',
  'David Guetta Featuring Usher',
  'David Houston',
  'David Lee Roth',
  'David Naughton',
  'David Ruffin',
  'David Soul',
  'Dawn',
  'Dazz Band',
  'Dean Friedman',
  'Debarge',
  'Debbie Gibson',
  'Debby Boone',
  'Debelah Morgan',
  'Deborah Cox',
  'Deeelite',
  'Deep Blue Something',
  'Deep Purple',
  'Def Leppard',
  'Default',
  'Del Amitri',
  'Del Shannon',
  'Delaney Bonnie Friends',
  'Delbert Mcclinton',
  'Dem Franchize Boyz',
  'Dem Franchize Boyz Featuring Jermaine Dupri Da Brat And Bow Wow',
  'Demi Lovato',
  'Deniece Williams',
  'Denise Lasalle',
  'Deodato',
  'Deon Estus',
  'Deon Jackson',
  'Depeche Mode',
  'Derek And The Dominos',
  'Desree',
  'Destinys Child',
  'Destinys Child Featuring Ti And Lil Wayne',
  'Dev',
  'Devo',
  'Dexys Midnight Runners',
  'Dht Featuring Edmee',
  'Diamond Rio',
  'Diana King',
  'Diana Ross',
  'Diana Ross Lionel Richie',
  'Diana Ross Marvin Gaye',
  'Dickey Lee',
  'Diddy Dirty Money Featuring Skylar Grey',
  'Diddy Featuring Keyshia Cole',
  'Dido',
  'Dierks Bentley',
  'Digable Planets',
  'Digital Underground',
  'Dino',
  'Dionne Farris',
  'Dionne Warwick',
  'Dire Straits',
  'Dirty Vegas',
  'Disclosure Featuring Sam Smith',
  'Dishwalla',
  'Divine',
  'Divinyls',
  'Dixie Chicks',
  'Dj Jazzy Jeff The Fresh Prince',
  'Dj Khaled Featuring Drake Rick Ross And Lil Wayne',
  'Dj Khaled Featuring Tpain Ludacris Snoop Dogg And Rick Ross',
  'Dj Kool',
  'Dj Sammy Featuring Yanou And Do',
  'Dj Snake And Alunageorge',
  'Dj Snake And Lil Jon',
  'Dmx',
  'Dna Featuring Suzanne Vega',
  'Do Or Die Featuring Twista',
  'Dobie Gray',
  'Dolly Parton',
  'Domino',
  'Don Henley',
  'Don Mclean',
  'Donell Jones',
  'Donna Fargo',
  'Donna Lewis',
  'Donna Summer',
  'Donna Summer And Brooklyn Dreams',
  'Donny Marie Osmond',
  'Donny Osmond',
  'Donovan',
  'Dorothy Moore',
  'Dr Buzzards Original Savannah Band',
  'Dr Dre',
  'Dr Dre Featuring Eminem',
  'Dr Dre Featuring Eminem And Skylar Grey',
  'Dr Dre Featuring Snoop Dogg',
  'Dr Dre Featuring Snoop Doggy Dogg',
  'Dr Hook',
  'Dr Hook The Medicine Show',
  'Dr John',
  'Drake',
  'Drake Featuring Kanye West Lil Wayne And Eminem',
  'Drake Featuring Lil Wayne',
  'Drake Featuring Majid Jordan',
  'Drake Featuring Rihanna',
  'Dream',
  'Dream Academy',
  'Drs',
  'Dru Hill',
  'Dru Hill Featuring Redman',
  'Duice',
  'Duncan Sheik',
  'Duran Duran',
  'Dusty Springfield',
  'Dwight Twilley Band',
  'E40 Featuring Tpain And Kandi Girl',
  'Eagles',
  'Earth Wind Fire',
  'Earth Wind Fire The Emotions',
  'Echosmith',
  'Ed Ames',
  'Ed Sheeran',
  'Eddie Holman',
  'Eddie Kendricks',
  'Eddie Money',
  'Eddie Murphy',
  'Eddie Rabbitt',
  'Eddie Rabbitt And Crystal Gayle',
  'Eddy Grant',
  'Edens Crush',
  'Edgar Winter Group',
  'Edie Brickell New Bohemians',
  'Edison Lighthouse',
  'Edward Bear',
  'Edward Maya Featuring Vika Jigulina',
  'Edwin Hawkins Singers',
  'Edwin Mccain',
  'Edwin Starr',
  'Eiffel 65',
  'El Debarge',
  'Electric Light Orchestra',
  'Eli Young Band',
  'Ella Henderson',
  'Elle King',
  'Ellie Goulding',
  'Elliott Yamin',
  'Elton John',
  'Elvin Bishop',
  'Elvis Presley',
  'Emeli Sande',
  'Emf',
  'Eminem',
  'Eminem Featuring Nate Dogg',
  'Eminem Featuring Rihanna',
  'En Vogue',
  'Engelbert Humperdinck',
  'England Dan John Ford Coley',
  'Enigma',
  'Enrique Iglesias',
  'Enrique Iglesias Featuring Descemer Bueno And Gente De Zona',
  'Enrique Iglesias Featuring Ludacris And Dj Frank E',
  'Enrique Iglesias Featuring Pitbull',
  'Enya',
  'Erasure',
  'Eric Benet Featuring Tamia',
  'Eric Burdon War',
  'Eric Carmen',
  'Eric Church',
  'Eric Clapton',
  'Erick Sermon Featuring Marvin Gaye',
  'Eruption',
  'Erykah Badu',
  'Estelle Featuring Kanye West',
  'Eternal',
  'Europe',
  'Eurythmics',
  'Evan And Jaron',
  'Evanescence',
  'Evanescence Featuring Paul Mccoy',
  'Eve 6',
  'Eve Featuring Alicia Keys',
  'Eve Featuring Gwen Stefani',
  'Evelyn Champagne King',
  'Everclear',
  'Everlast',
  'Every Mothers Son',
  'Everything But The Girl',
  'Exile',
  'Expose',
  'Extreme',
  'Fabolous Featuring Lil Mo And Mike Shorey',
  'Fabolous Featuring Neyo',
  'Fabolous Featuring Tamia',
  'Fabolous Featuring Thedream',
  'Faith Evans',
  'Faith Evans Featuring Puff Daddy',
  'Faith Hill',
  'Faith No More',
  'Falco',
  'Fall Out Boy',
  'Fancy',
  'Fantasia',
  'Far East Movement Featuring Ryan Tedder',
  'Far East Movement Featuring The Cataracs And Dev',
  'Fastball',
  'Fat Joe Featuring Ashanti',
  'Fat Joe Featuring Lil Wayne',
  'Fat Joe Featuring Nelly',
  'Fat Joe Featuring R Kelly',
  'Fergie',
  'Fergie Featuring Ludacris',
  'Fergie Featuring William',
  'Fetty Wap',
  'Fetty Wap Featuring Monty',
  'Fetty Wap Featuring Remy Boyz',
  'Field Mob',
  'Field Mob Featuring Ciara',
  'Fifth Harmony Featuring Kid Ink',
  'Filter',
  'Fine Young Cannibals',
  'Finger Eleven',
  'Firefall',
  'Firehouse',
  'Five',
  'Five Americans',
  'Five For Fighting',
  'Five Man Electrical Band',
  'Five Stairsteps',
  'Fleetwood Mac',
  'Flo Rida',
  'Flo Rida Featuring David Guetta',
  'Flo Rida Featuring Sage The Gemini And Lookas',
  'Flo Rida Featuring Sia',
  'Flo Rida Featuring Tpain',
  'Flo Rida Featuring William',
  'Flo Rida Featuring Wynter Gordon',
  'Floetry',
  'Florida Georgia Line',
  'Florida Georgia Line Featuring Luke Bryan',
  'Florida Georgia Line Featuring Nelly',
  'Focus',
  'Foghat',
  'Foo Fighters',
  'Force Mds',
  'Foreigner',
  'Fort Minor Featuring Holly Brook And Jonah Matranga',
  'Foster The People',
  'Four Tops',
  'Foxy',
  'Foxy Brown Featuring Jayz',
  'Frank Nancy Sinatra',
  'Frank Sinatra',
  'Frank Stallone',
  'Franke And The Knockouts',
  'Frankie J',
  'Frankie J Featuring Baby Bash',
  'Frankie Valli',
  'Freak Nasty',
  'Freda Payne',
  'Freddie Hart',
  'Freddy Fender',
  'Free',
  'Frida',
  'Friend Lover',
  'Frijid Pink',
  'Fuel',
  'Fun',
  'Fun Featuring Janelle Mon Ae',
  'Gabrielle',
  'Gallery',
  'Gary Lewis The Playboys',
  'Gary Lewis And The Playboys',
  'Gary Numan',
  'Gary Puckett The Union Gap',
  'Gary Us Bonds',
  'Gary Wright',
  'Gavin Degraw',
  'Gavin Rossdale',
  'Gene Debbe',
  'Gene Chandler',
  'General Public',
  'Genesis',
  'George Benson',
  'George Duke Stanley Clarke',
  'George Ezra',
  'George Harrison',
  'George Mccrae',
  'George Michael',
  'George Michael And Elton John',
  'George Strait',
  'Georgia Satellites',
  'Georgie Fame',
  'Gerald Levert',
  'Gerardo',
  'Gerry And The Pacemakers',
  'Gerry Rafferty',
  'Ghost Town Djs',
  'Gilbert Osullivan',
  'Gin Blossoms',
  'Gina G',
  'Gino Vannelli',
  'Ginuwine',
  'Ginuwine Featuring Baby',
  'Gladys Knight The Pips',
  'Glass Tiger',
  'Glen Campbell',
  'Glenn Frey',
  'Glenn Medeiros',
  'Glenn Medeiros And Bobby Brown',
  'Glenn Yarbrough',
  'Gloria Estefan',
  'Gloria Estefan And Miami Sound Machine',
  'Gloria Gaynor',
  'Gloria Loring And Carl Anderson',
  'Gnarls Barkley',
  'Go West',
  'Golden Earring',
  'Goo Goo Dolls',
  'Gordon Lightfoot',
  'Gorillaz',
  'Gotye Featuring Kimbra',
  'Gq',
  'Grand Funk',
  'Grand Funk Railroad',
  'Great White',
  'Green Day',
  'Green Jell Y',
  'Greg Guidry',
  'Gregory Abbott',
  'Gretchen Wilson',
  'Groove Theory',
  'Grover Washington Jr Bill Withers',
  'Gunit Featuring Joe',
  'Guns N Roses',
  'Gwen Stefani',
  'Gwen Stefani Featuring Akon',
  'Gwen Stefani Featuring Eve',
  'Gym Class Heroes Featuring Adam Levine',
  'Gym Class Heroes Featuring Neon Hitch',
  'Gym Class Heroes Featuring Patrick Stump',
  'Haddaway',
  'Hall Oates',
  'Hamilton Joe Frank Reynolds',
  'Hammer',
  'Hanson',
  'Harold Melvin The Blue Notes',
  'Harry Chapin',
  'Harry Nilsson',
  'Havana Brown Featuring Pitbull',
  'Heart',
  'Heatwave',
  'Heavy D',
  'Heavy D The Boyz',
  'Helen Reddy',
  'Hellogoodbye',
  'Henry Gross',
  'Henry Mancini',
  'Herb Alpert',
  'Hermans Hermits',
  'Hifive',
  'High Inergy',
  'Hinder',
  'Honey Cone',
  'Hoobastank',
  'Hootie The Blowfish',
  'Horst Jankowski',
  'Hot',
  'Hot Chelle Rae',
  'Hot Chocolate',
  'House Of Pain',
  'Houston Featuring Chingy Nate Dogg And I20',
  'Howard Jones',
  'Howie Day',
  'Hozier',
  'Htown',
  'Huey',
  'Huey Lewis And The News',
  'Hugh Masekela',
  'Hugo Montenegro',
  'Hunter Hayes',
  'Hurricane Chris',
  'Hurricane Smith',
  'Ian Matthews',
  'Ian Whitcomb',
  'Ice Cube',
  'Ice Cube Featuring Das Efx',
  'Ice Cube Featuring George Clinton',
  'Icehouse',
  'Icona Pop Featuring Charli Xcx',
  'Idina Menzel',
  'Iggy Azalea Featuring Charli Xcx',
  'Iggy Azalea Featuring Rita Ora',
  'Ike Tina Turner',
  'Ilovemakonnen Featuring Drake',
  'Ilovememphis',
  'Imagine Dragons',
  'Immature',
  'Incubus',
  'Ini Kamoze',
  'Inner Circle',
  'Inoj',
  'Instant Funk',
  'Inxs',
  'Irene Cara',
  'Isaac Hayes',
  'Iyaz',
  'J Cole',
  'J Cole Featuring Miguel',
  'J Holiday',
  'Ja Rule Featuring Ashanti',
  'Ja Rule Featuring Ashanti Charli Baltimore And Vita',
  'Ja Rule Featuring Case',
  'Ja Rule Featuring Lil Mo And Vita',
  'Ja Rule Featuring R Kelly And Ashanti',
  'Jack Jones',
  'Jack Wagner',
  'Jackie Deshannon',
  'Jackie Wilson',
  'Jackson Browne',
  'Jadakiss',
  'Jade',
  'Jagged Edge',
  'Jagged Edge Featuring Nelly',
  'Jaheim',
  'Jaheim Featuring Next',
  'Jake Owen',
  'James Bobby Purify',
  'James Blunt',
  'James Brown',
  'James Ingram And Michael Mcdonald',
  'James Newton Howard Featuring Jennifer Lawrence',
  'James Taylor',
  'Jamie Foxx Featuring Ludacris',
  'Jamie Foxx Featuring Tpain',
  'Jamie Walters',
  'Jane Child',
  'Janet',
  'Janet Jackson',
  'Janet Jackson Featuring Blackstreet',
  'Janis Ian',
  'Janis Joplin',
  'Jann Arden',
  'Jason Aldean',
  'Jason Aldean Featuring Kelly Clarkson',
  'Jason Der Ulo',
  'Jason Derulo',
  'Jason Derulo Featuring 2 Chainz',
  'Jason Derulo Featuring Snoop Dogg',
  'Jason Mraz',
  'Jay The Techniques',
  'Jay And The Americans',
  'Jay Ferguson',
  'Jay Sean Featuring Lil Wayne',
  'Jay Sean Featuring Sean Paul And Lil Jon',
  'Jay Z Featuring Justin Timberlake',
  'Jayz',
  'Jayz And Alicia Keys',
  'Jayz And Kanye West',
  'Jayz Featuring Amil And Ja Rule',
  'Jayz Featuring Mr Hudson',
  'Jayz Featuring Rihanna And Kanye West',
  'Jayz Featuring Ugk',
  'Jd Souther',
  'Jean Knight',
  'Jeannie C Riley',
  'Jefferson Airplane',
  'Jefferson Starship',
  'Jennifer Lopez',
  'Jennifer Lopez Featuring Ja Rule',
  'Jennifer Lopez Featuring Jadakiss And Styles P',
  'Jennifer Lopez Featuring Ll Cool J',
  'Jennifer Lopez Featuring Nas',
  'Jennifer Lopez Featuring Pitbull',
  'Jennifer Paige',
  'Jennifer Warnes',
  'Jeremih',
  'Jeremih Featuring 50 Cent',
  'Jeremih Featuring Yg',
  'Jeremy Jordan',
  'Jermaine Dupri Featuring Da Brat And Usher',
  'Jermaine Jackson',
  'Jermaine Stewart',
  'Jerrod Niemann',
  'Jerry Butler',
  'Jerry Reed',
  'Jesse Mccartney',
  'Jesse Mccartney Featuring Ludacris',
  'Jesse Powell',
  'Jessi Colter',
  'Jessica Andrews',
  'Jessica Simpson',
  'Jessie J',
  'Jessie J Ariana Grande And Nicki Minaj',
  'Jessie J Featuring Bob',
  'Jesus Jones',
  'Jet',
  'Jethro Tull',
  'Jewel',
  'Jewel Akens',
  'Jibbs',
  'Jidenna Featuring Roman Gianarthur',
  'Jim Croce',
  'Jim Jones',
  'Jim Jones Featuring Ron Browz And Juelz Santana',
  'Jim Stafford',
  'Jimmy Buffett',
  'Jimmy Castor Bunch',
  'Jimmy Cliff',
  'Jimmy Eat World',
  'Jimmy Ray',
  'Jimmy Ruffin',
  'Jive Bunny And The Mastermixers',
  'Jkwon',
  'Jo Dee Messina',
  'Joan Baez',
  'Joan Jett The Blackhearts',
  'Joan Jett And The Blackhearts',
  'Joan Osborne',
  'Jodeci',
  'Jody Watley',
  'Joe',
  'Joe Cocker',
  'Joe Cocker And Jennifer Warnes',
  'Joe Featuring Mystikal',
  'Joe Jackson',
  'Joe Public',
  'Joe Simon',
  'Joe South',
  'Joe Tex',
  'Joe Walsh',
  'Joey Lawrence',
  'Joey Mcintyre',
  'Joey Scarbury',
  'John Cafferty The Beaver Brown Band',
  'John Cougar',
  'John Cougar Mellencamp',
  'John Denver',
  'John Fred His Playboy Band',
  'John Legend',
  'John Legend Featuring Andre 3000',
  'John Lennon',
  'John Mayer',
  'John Mellencamp',
  'John Mellencamp Featuring Meshell Ndegeocello',
  'John Michael Montgomery',
  'John Parr',
  'John Paul Young',
  'John Schneider',
  'John Sebastian',
  'John Stewart',
  'John Travolta',
  'John Waite',
  'Johnnie Taylor',
  'Johnny Cash',
  'Johnny Gill',
  'Johnny Hates Jazz',
  'Johnny Maestro The Brooklyn Bridge',
  'Johnny Mathis Deniece Williams',
  'Johnny Nash',
  'Johnny Rivers',
  'Jojo',
  'Jon B',
  'Jon Bon Jovi',
  'Jon Secada',
  'Jonas Brothers Featuring Big Rob',
  'Jonathan Edwards',
  'Joni Mitchell',
  'Jordan Knight',
  'Jordin Sparks',
  'Jordin Sparks And Chris Brown',
  'Jose Feliciano',
  'Joshua Kadison',
  'Journey',
  'Jt Money Featuring Sole',
  'Jud Strunk',
  'Judy Collins',
  'Juelz Santana',
  'Juice Newton',
  'Julian Lennon',
  'Julio Iglesias And Willie Nelson',
  'Junior Mafia Featuring The Notorious Big',
  'Junior Walker The All Stars',
  'Justin Bieber',
  'Justin Bieber Featuring Big Sean',
  'Justin Bieber Featuring Ludacris',
  'Justin Bieber Featuring Nicki Minaj',
  'Justin Timberlake',
  'Justin Timberlake Featuring Ti',
  'Justin Timberlake Featuring Timbaland',
  'Juvenile Featuring Mannie Fresh And Lil Wayne',
  'Juvenile Featuring Soulja Slim',
  'Kajagoogoo',
  'Kandi',
  'Kansas',
  'Kanye West',
  'Kanye West Featuring Dwele',
  'Kanye West Featuring Jamie Foxx',
  'Kanye West Featuring Rihanna',
  'Kanye West Featuring Syleena Johnson',
  'Kanye West Featuring Tpain',
  'Kardinal Offishall Featuring Akon',
  'Karla Bonoff',
  'Karmin',
  'Karyn White',
  'Kathy Troccoli',
  'Katrina And The Waves',
  'Katy Perry',
  'Katy Perry Featuring Juicy J',
  'Katy Perry Featuring Kanye West',
  'Katy Perry Featuring Snoop Dogg',
  'Kc And The Sunshine Band',
  'Keha',
  'Keha Featuring 3oh3',
  'Keith',
  'Keith Carradine',
  'Keith Sweat',
  'Keith Sweat Featuring Athena Cage',
  'Keith Urban',
  'Kelis',
  'Kelis Featuring Too Short',
  'Kelly Clarkson',
  'Kelly Price Featuring R Kelly And Ron Isley',
  'Kelly Rowland Featuring Lil Wayne',
  'Kendrick Lamar',
  'Kenny Chesney',
  'Kenny Chesney Featuring Grace Potter',
  'Kenny Chesney Featuring Uncle Kracker',
  'Kenny Loggins',
  'Kenny Loggins Stevie Nicks',
  'Kenny Nolan',
  'Kenny Rogers',
  'Kenny Rogers Kim Carnes',
  'Kenny Rogers And Dolly Parton',
  'Kenny Rogers And Sheena Easton',
  'Keri Hilson',
  'Keri Hilson Featuring Kanye West And Neyo',
  'Keri Hilson Featuring Lil Wayne',
  'Kesha',
  'Kevin Lyttle',
  'Kevin Rudolf Featuring Birdman Jay Sean And Lil Wayne',
  'Kevin Rudolf Featuring Lil Wayne',
  'Kevon Edmonds',
  'Keyshia Cole',
  'Keyshia Cole Featuring Missy Elliott And Lil Kim',
  'Kid Cudi',
  'Kid Ink Featuring Chris Brown',
  'Kid Rock',
  'Kid Rock Featuring Sheryl Crow',
  'Kim Carnes',
  'Kim Wilde',
  'King Floyd',
  'King Harvest',
  'Kings Of Leon',
  'Kip Moore',
  'Kirko Bangz',
  'Kiss',
  'Klymaxx',
  'Kongos',
  'Kool The Gang',
  'Kris Kristofferson',
  'Kris Kross',
  'Kristinia Debarge',
  'Kt Tunstall',
  'Kws',
  'Kylie Minogue',
  'La Bouche',
  'La Roux',
  'Labelle',
  'Lady Antebellum',
  'Lady Gaga',
  'Lady Gaga Featuring Beyonce',
  'Lady Gaga Featuring Colby Odonis',
  'Lady Gaga Featuring R Kelly',
  'Lamont Dozier',
  'Lana Del Rey And Cedric Gervais',
  'Larry Groce',
  'Laura Branigan',
  'Lauryn Hill',
  'Leann Rimes',
  'Leblanc Carr',
  'Lee Ann Womack',
  'Lee Brice',
  'Lee Dorsey',
  'Lee Michaels',
  'Leif Garrett',
  'Len',
  'Lenny Kravitz',
  'Leo Sayer',
  'Leona Lewis',
  'Lesley Gore',
  'Level 42',
  'Levert',
  'Lfo',
  'Lifehouse',
  'Lil Bow Wow Featuring Xscape',
  'Lil Flip',
  'Lil Flip Featuring Lea',
  'Lil Jon The East Side Boyz Featuring Ying Yang Twins',
  'Lil Jon Featuring E40 And Sean Paul',
  'Lil Jon Featuring Usher And Ludacris',
  'Lil Kim Featuring 50 Cent',
  'Lil Kim Featuring Da Brat Left Eye Missy Elliott And Angie Martinez',
  'Lil Kim Featuring Mr Cheeks',
  'Lil Kim Featuring Puff Daddy',
  'Lil Mo Featuring Fabolous',
  'Lil Romeo',
  'Lil Wayne',
  'Lil Wayne Featuring Bobby Valentino',
  'Lil Wayne Featuring Cory Gunz',
  'Lil Wayne Featuring Drake',
  'Lil Wayne Featuring Drake And Future',
  'Lil Wayne Featuring Static Major',
  'Lil Wayne Featuring Tpain',
  'Linda Ronstadt',
  'Linda Ronstadt And Aaron Neville',
  'Linda Ronstadt And James Ingram',
  'Lindsey Buckingham',
  'Linear',
  'Linkin Park',
  'Lionel Richie',
  'Lipps Inc',
  'Lisa Lisa And Cult Jam',
  'Lisa Loeb',
  'Lisa Loeb And Nine Stories',
  'Lisa Stansfield',
  'Lita Ford And Ozzy Osbourne',
  'Little Anthony And The Imperials',
  'Little Big Town',
  'Little River Band',
  'Ll Cool J',
  'Lloyd',
  'Lloyd Banks',
  'Lloyd Featuring Ashanti',
  'Lloyd Featuring Lil Wayne',
  'Lmfao',
  'Lmfao Featuring Lauren Bennett And Goonrock',
  'Lobo',
  'Londonbeat',
  'Lonestar',
  'Looking Glass',
  'Lord Tariq And Peter Gunz',
  'Lorde',
  'Loreena Mckennitt',
  'Los Bravos',
  'Los Del R Io',
  'Los Lobos',
  'Los Lonely Boys',
  'Lou Bega',
  'Lou Christie',
  'Lou Gramm',
  'Lou Rawls',
  'Love And Rockets',
  'Love Unlimited',
  'Loverboy',
  'Lovin Spoonful',
  'Lsg',
  'Ltd',
  'Ludacris',
  'Ludacris Featuring Bobby Valentino',
  'Ludacris Featuring Mary J Blige',
  'Ludacris Featuring Mystikal And I20',
  'Ludacris Featuring Nicki Minaj',
  'Ludacris Featuring Pharrell',
  'Ludacris Featuring Shawnna',
  'Luke Bryan',
  'Luke Featuring No Good But So Good',
  'Lulu',
  'Lumidee',
  'Luniz',
  'Lupe Fiasco',
  'Lupe Fiasco Featuring Matthew Santos',
  'Luscious Jackson',
  'Luther Ingram',
  'Luther Vandross',
  'Luther Vandross And Janet Jackson',
  'Luther Vandross And Mariah Carey',
  'Lynn Anderson',
  'Lynyrd Skynyrd',
  'M',
  'M Otley Cr Ue',
  'M Ya',
  'M Ya And Sisqo',
  'Mac And Katie Kissoon',
  'Mac Davis',
  'Macklemore Ryan Lewis Featuring Schoolboy Q And Hollis',
  'Macklemore And Ryan Lewis Featuring Eric Nally Melle Mel Kool Moe Dee And Grandmaster Caz',
  'Macklemore And Ryan Lewis Featuring Mary Lambert',
  'Macklemore And Ryan Lewis Featuring Ray Dalton',
  'Macklemore And Ryan Lewis Featuring Wanz',
  'Macy Gray',
  'Madness',
  'Madonna',
  'Madonna Featuring Justin Timberlake And Timbaland',
  'Magic',
  'Major Harris',
  'Major Lazer And Dj Snake Featuring Mo',
  'Mama Cass Elliot',
  'Manfred Mann',
  'Manfred Manns Earth Band',
  'Marc Anthony',
  'Marcy Playground',
  'Maria Muldaur',
  'Mariah Carey',
  'Mariah Carey And Boyz Ii Men',
  'Mariah Carey Featuring Cameo',
  'Mariah Carey Featuring Jayz',
  'Mariah Carey Featuring Joe And 98 Degrees',
  'Mariah Carey Featuring Miguel',
  'Mario',
  'Mario Featuring Gucci Mane And Sean Garrett',
  'Mario Winans Featuring Enya And P Diddy',
  'Mark Chesnutt',
  'Mark Lindsay',
  'Mark Morrison',
  'Mark Ronson Featuring Bruno Mars',
  'Mark Wills',
  'Marky Mark And The Funky Bunch',
  'Marky Mark And The Funky Bunch Featuring Loleatta Holloway',
  'Marmalade',
  'Maroon 5',
  'Maroon 5 Featuring Christina Aguilera',
  'Maroon 5 Featuring Wiz Khalifa',
  'Martha And The Vandellas',
  'Martika',
  'Martin Garrix',
  'Martin Page',
  'Marty Balin',
  'Marvin Gaye',
  'Marvin Gaye Tammi Terrell',
  'Mary Hopkin',
  'Mary J Blige',
  'Mary J Blige Featuring Ja Rule',
  'Mary Jane Girls',
  'Mary Macgregor',
  'Mary Mary',
  'Mase Featuring Kelly Price',
  'Mase Featuring Puff Daddy',
  'Mase Featuring Total',
  'Master P Featuring Fiend Silkk The Shocker Mia X And Mystikal',
  'Master P Featuring Sons Of Funk',
  'Matchbox 20',
  'Matchbox Twenty',
  'Matthew Wilder',
  'Matthews Southern Comfort',
  'Maureen Mcgovern',
  'Maxi Priest',
  'Maxi Priest Featuring Shaggy',
  'Maxine Nightingale',
  'Maxwell',
  'Mc Hammer',
  'Mc Lyte',
  'Mc Lyte Featuring Xscape',
  'Mcfadden Whitehead',
  'Meat Loaf',
  'Meek Mill Featuring Chris Brown And Nicki Minaj',
  'Meghan Trainor',
  'Meghan Trainor Featuring John Legend',
  'Mel And Tim',
  'Mel Carter',
  'Melanie',
  'Melissa Etheridge',
  'Melissa Manchester',
  'Mellow Man Ace',
  'Men At Work',
  'Men Without Hats',
  'Mercy',
  'Meredith Brooks',
  'Merril Bainbridge',
  'Merrilee Rush',
  'Metallica',
  'Metro Station',
  'Mfsb',
  'Mia',
  'Miami Sound Machine',
  'Michael Bolton',
  'Michael Buble',
  'Michael Damian',
  'Michael Franti Spearhead Featuring Cherine Anderson',
  'Michael Jackson',
  'Michael Jackson And Janet Jackson',
  'Michael Jackson And Justin Timberlake',
  'Michael Jackson And Paul Mccartney',
  'Michael Jackson With Siedah Garrett',
  'Michael Johnson',
  'Michael Martin Murphey',
  'Michael Mcdonald',
  'Michael Sembello',
  'Michael W Smith',
  'Michelle',
  'Michelle Branch',
  'Mickey Gilley',
  'Miguel',
  'Mike The Mechanics',
  'Mike Jones',
  'Mike Oldfield',
  'Mike Posner',
  'Mike Reno And Ann Wilson',
  'Miley Cyrus',
  'Milli Vanilli',
  'Mims',
  'Minnie Riperton',
  'Mint Condition',
  'Miranda Lambert',
  'Miranda Lambert And Carrie Underwood',
  'Missy Elliott',
  'Missy Elliott Featuring Ciara And Fatman Scoop',
  'Missy Elliott Featuring Da Brat',
  'Missy Elliott Featuring Ludacris',
  'Missy Elliott Featuring Nas Eve And Qtip',
  'Mkto',
  'Mo Thugs',
  'Moby Featuring Gwen Stefani',
  'Mocedades',
  'Mokenstef',
  'Monica',
  'Monifah',
  'Montell Jordan',
  'Montell Jordan Featuring Master P And Silkk The Shocker',
  'Moody Blues',
  'Morris Albert',
  'Motherlode',
  'Mountain',
  'Mouth Macneal',
  'Moving Pictures',
  'Mr Big',
  'Mr Cheeks',
  'Mr Mister',
  'Mr President',
  'Mr Probz',
  'Mumford Sons',
  'Mungo Jerry',
  'Murray Head',
  'Musical Youth',
  'Musiq Soulchild',
  'My Chemical Romance',
  'Mystikal',
  'Mystikal Featuring Nivea',
  'N Ii U',
  'N Sync',
  'N Sync And Gloria Estefan',
  'N Sync Featuring Nelly',
  'N2deep',
  'Naked Eyes',
  'Nancy Sinatra',
  'Nas',
  'Nas And Bravehearts',
  'Natalie',
  'Natalie Cole',
  'Natalie La Rose Featuring Jeremih',
  'Natalie Merchant',
  'Natasha Bedingfield',
  'Natasha Bedingfield Featuring Sean Kingston',
  'Natural Selection',
  'Naughty Boy Featuring Sam Smith',
  'Naughty By Nature',
  'Naughty By Nature Featuring Zhane',
  'Nazareth',
  'Neil Diamond',
  'Neil Sedaka',
  'Neil Young',
  'Nelly',
  'Nelly Featuring City Spud',
  'Nelly Featuring Jaheim',
  'Nelly Featuring Kelly Rowland',
  'Nelly Featuring St Lunatics',
  'Nelly Featuring Tim Mcgraw',
  'Nelly Furtado',
  'Nelly Furtado Featuring Timbaland',
  'Nelly P Diddy And Murphy Lee',
  'Nelly Paul Wall And Ali Gipp',
  'Nelson',
  'Nena',
  'Neneh Cherry',
  'Neon Trees',
  'New Boyz Featuring Ray J',
  'New Boyz Featuring The Cataracs And Dev',
  'New Colony Six',
  'New Edition',
  'New Kids On The Block',
  'New Vaudeville Band',
  'New York City',
  'Next',
  'Neyo',
  'Nick Cannon Featuring R Kelly',
  'Nick Gilder',
  'Nick Jonas',
  'Nick Lachey',
  'Nickelback',
  'Nicki French',
  'Nicki Minaj',
  'Nicki Minaj Featuring Drake',
  'Nicki Minaj Featuring Drake And Lil Wayne',
  'Nicki Minaj Featuring Drake Lil Wayne And Chris Brown',
  'Nicky Jam And Enrique Iglesias',
  'Nico Vinz',
  'Nicole Featuring Missy Elliott And Mocha',
  'Nigel Olsson',
  'Night Ranger',
  'Nina Sky',
  'Nine Days',
  'Nirvana',
  'Nivea Featuring Jagged Edge',
  'No Doubt',
  'No Doubt Featuring Bounty Killer',
  'No Doubt Featuring Lady Saw',
  'No Mercy',
  'Norah Jones',
  'Nore',
  'Norman Greenbaum',
  'Nu Flavor',
  'O C Smith',
  'Oasis',
  'Ocean',
  'Odyssey',
  'Of Monsters And Men',
  'Ohio Express',
  'Ohio Players',
  'Oleta Adams',
  'Oliver',
  'Olivia Newtonjohn',
  'Olly Murs Featuring Flo Rida',
  'Omarion',
  'Omarion Featuring Chris Brown And Jhene Aiko',
  'Omarion Featuring Timbaland',
  'Omi',
  'One Direction',
  'Onerepublic',
  'Onyx',
  'Orchestral Manoeuvres In The Dark',
  'Orianthi',
  'Orleans',
  'Ot Genasis',
  'Otis Redding',
  'Otown',
  'Outkast',
  'Outkast Featuring Killer Mike',
  'Outkast Featuring Sleepy Brown',
  'Owl City',
  'Owl City And Carly Rae Jepsen',
  'Ozark Mountain Daredevils',
  'P Diddy Featuring Ginuwine Loon And Mario Winans',
  'P Diddy Featuring Usher And Loon',
  'Pablo Cruise',
  'Pacific Gas Electric',
  'Panic At The Disco',
  'Papa Roach',
  'Paper Lace',
  'Paperboy',
  'Paramore',
  'Parliament',
  'Passenger',
  'Pat Benatar',
  'Patrick Hernandez',
  'Patrick Swayze Featuring Wendy Fraser',
  'Patti Austin And James Ingram',
  'Patti Labelle And Michael Mcdonald',
  'Patti Page',
  'Patty Duke',
  'Patty Smyth',
  'Paul Linda Mccartney',
  'Paul Anka',
  'Paul Carrack',
  'Paul Davis',
  'Paul Mccartney',
  'Paul Mccartney Wings',
  'Paul Mccartney And Michael Jackson',
  'Paul Mccartney And Stevie Wonder',
  'Paul Mccartney And Wings',
  'Paul Revere The Raiders',
  'Paul Simon',
  'Paul Stookey',
  'Paul Young',
  'Paula Abdul',
  'Paula Abdul And The Wild Pair',
  'Paula Cole',
  'Paula Deanda Featuring The Dey',
  'Peabo Bryson',
  'Peabo Bryson And Regina Belle',
  'Peabo Bryson And Roberta Flack',
  'Peaches Herb',
  'Pearl Jam',
  'Pebbles',
  'People',
  'Percy Sledge',
  'Perry Como',
  'Pet Shop Boys',
  'Pet Shop Boys With Dusty Springfield',
  'Pete Townshend',
  'Peter And Gordon',
  'Peter Brown',
  'Peter Cetera',
  'Peter Cetera And Amy Grant',
  'Peter Frampton',
  'Peter Gabriel',
  'Peter Mccann',
  'Peter Paul And Mary',
  'Peter Schilling',
  'Petey Pablo',
  'Petula Clark',
  'Pharrell Featuring Jayz',
  'Pharrell Williams',
  'Phil Collins',
  'Phil Collins And Marilyn Martin',
  'Philip Bailey And Phil Collins',
  'Phillip Phillips',
  'Phoebe Snow',
  'Pilot',
  'Pink',
  'Pink Featuring Nate Ruess',
  'Pink Floyd',
  'Pitbull',
  'Pitbull And Neyo',
  'Pitbull Featuring Chris Brown',
  'Pitbull Featuring Christina Aguilera',
  'Pitbull Featuring Kesha',
  'Pitbull Featuring Neyo Afrojack And Nayer',
  'Pitbull Featuring Tpain',
  'Plain White Ts',
  'Planet Soul',
  'Player',
  'Plies Featuring Akon',
  'Plies Featuring Neyo',
  'Plies Featuring Tpain',
  'Pm Dawn',
  'Pointer Sisters',
  'Poison',
  'Portrait',
  'Positive K',
  'Power Station',
  'Pras Michel Featuring Ol Dirty Bastard And M Ya',
  'Pretty Poison',
  'Pretty Ricky',
  'Prince',
  'Prince And The New Power Generation',
  'Prince And The Revolution',
  'Procol Harum',
  'Pseudo Echo',
  'Psy',
  'Puddle Of Mudd',
  'Puff Daddy Featuring Faith Evans And 112',
  'Puff Daddy Featuring Mase',
  'Puff Daddy Featuring R Kelly',
  'Puff Daddy Featuring The Notorious Big And Busta Rhymes',
  'Puff Daddy Featuring The Notorious Big And Mase',
  'Pure Prairie League',
  'Pussycat Dolls',
  'Pussycat Dolls Featuring Snoop Dogg',
  'Pussycat Dolls Featuring William',
  'Quad City Djs',
  'Quarterflash',
  'Queen',
  'Queen Latifah',
  'Queensr Yche',
  'Quiet Riot',
  'Quincy Jones Featuring James Ingram',
  'R City Featuring Adam Levine',
  'R Dean Taylor',
  'R Kelly',
  'R Kelly And Celine Dion',
  'R Kelly Featuring Jayz',
  'R Kelly Featuring The Isley Brothers',
  'R Kelly Featuring Ti And Tpain',
  'R Kelly Featuring Usher',
  'Rachel Platten',
  'Rae Sremmurd',
  'Ralph Tresvant',
  'Randy Houser',
  'Randy Newman',
  'Randy Vanwarmer',
  'Raphael Saadiq',
  'Rare Earth',
  'Rascal Flatts',
  'Raspberries',
  'Ratt',
  'Ray Charles',
  'Ray Conniff Singers',
  'Ray Goodman Brown',
  'Ray J',
  'Ray J Featuring Yung Berg',
  'Ray Parker Jr',
  'Ray Stevens',
  'Raydio',
  'Ready For The World',
  'Real Mccoy',
  'Red Hot Chili Peppers',
  'Redbone',
  'Rednex',
  'Regina',
  'Rem',
  'Reo Speedwagon',
  'Restless Heart',
  'Rex Smith',
  'Rich Boy Featuring Polow Da Don',
  'Rich Gang Featuring Young Thug And Rich Homie Quan',
  'Rich Homie Quan',
  'Richard Harris',
  'Richard Marx',
  'Richie Havens',
  'Rick Astley',
  'Rick James',
  'Rick Ross Featuring Tpain',
  'Rick Springfield',
  'Rickie Lee Jones',
  'Ricky Martin',
  'Ricky Martin And Christina Aguilera',
  'Ricky Nelson',
  'Right Said Fred',
  'Rihanna',
  'Rihanna Featuring Calvin Harris',
  'Rihanna Featuring Chris Brown',
  'Rihanna Featuring Drake',
  'Rihanna Featuring Jayz',
  'Rihanna Featuring Jeezy',
  'Rihanna Featuring Mikky Ekko',
  'Rihanna Featuring Neyo',
  'Rihanna Featuring Sean Paul',
  'Rihanna Kanye West And Paul Mccartney',
  'Ringo Starr',
  'Rita Coolidge',
  'Rixton',
  'Rob Thomas',
  'Robbie Dupree',
  'Robbie Nevil',
  'Robert John',
  'Robert Knight',
  'Robert Palmer',
  'Robert Parker',
  'Roberta Flack',
  'Roberta Flack Donny Hathaway',
  'Robin Mcnamara',
  'Robin S',
  'Robin Thicke',
  'Robin Thicke Featuring Ti And Pharrell',
  'Robin Thicke Featuring Ti And Pharrell Williams',
  'Robyn',
  'Rocko Featuring Future And Rick Ross',
  'Rockwell',
  'Rocky Burnette',
  'Rod Stewart',
  'Rodney Atkins',
  'Roger Miller',
  'Roger Voudouris',
  'Roger Williams',
  'Ronnie Dyson',
  'Ronnie Milsap',
  'Rosanne Cash',
  'Rose Royce',
  'Roxette',
  'Roy Head',
  'Ruben Studdard',
  'Ruff Endz',
  'Rufus',
  'Rufus Chaka Khan',
  'Rupert Holmes',
  'Ryan Cabrera',
  'S Club 7',
  'Sade',
  'Safire',
  'Sailcat',
  'Sam Dave',
  'Sam And Dave',
  'Sam Cooke',
  'Sam Hunt',
  'Sam Smith',
  'Sam The Sham And The Pharaohs',
  'Samantha Fox',
  'Samantha Mumba',
  'Sammi Smith',
  'Sammie',
  'Sammy Davis Jr',
  'Sammy Hagar',
  'Sammy Johns',
  'Sandy Posey',
  'Sanfordtownsend Band',
  'Santa Esmeralda',
  'Santana',
  'Santana Featuring Chad Kroeger',
  'Santana Featuring Michelle Branch',
  'Santana Featuring Rob Thomas',
  'Santana Featuring The Product Gb',
  'Sara Bareilles',
  'Sarah Mclachlan',
  'Savage Garden',
  'Saving Abel',
  'Scarface Featuring 2pac And Johnny P',
  'Schoolboy Q Featuring Bj The Chicago Kid',
  'Scorpions',
  'Scott Mckenzie',
  'Scritti Politti',
  'Seal',
  'Seals And Crofts',
  'Sean Kingston',
  'Sean Kingston And Justin Bieber',
  'Sean Paul',
  'Sean Paul Featuring Keyshia Cole',
  'Sean Paul Featuring Sasha',
  'Secondhand Serenade',
  'Seduction',
  'Selena Gomez',
  'Selena Gomez The Scene',
  'Selena Gomez Featuring Aap Rocky',
  'Sergio Mendes',
  'Shaggy',
  'Shaggy Featuring Rikrok',
  'Shai',
  'Shakespears Sister',
  'Shakira',
  'Shakira Featuring Alejandro Sanz',
  'Shakira Featuring Rihanna',
  'Shakira Featuring Wyclef Jean',
  'Shalamar',
  'Shania Twain',
  'Shanice',
  'Shannon',
  'Shaun Cassidy',
  'Shawn Colvin',
  'Shawn Mendes',
  'Shawn Mullins',
  'Sheena Easton',
  'Sheila E',
  'Sheriff',
  'Sheryl Crow',
  'Shinedown',
  'Shirley Bassey',
  'Shirley Ellis',
  'Shocking Blue',
  'Shontelle',
  'Shop Boyz',
  'Shorty Long',
  'Sia',
  'Silento',
  'Silk',
  'Silver',
  'Silver Convention',
  'Simon Garfunkel',
  'Simple Minds',
  'Simply Red',
  'Sinead Oconnor',
  'Sir Douglas Quintet',
  'Sir Mixalot',
  'Sisqo',
  'Sister Hazel',
  'Sister Janet Mead',
  'Sister Sledge',
  'Sixpence None The Richer',
  'Skeelo',
  'Skid Row',
  'Skrillex And Diplo Featuring Justin Bieber',
  'Skylark',
  'Slim Harpo',
  'Sly The Family Stone',
  'Sly Fox',
  'Smash Mouth',
  'Smith',
  'Smokey Robinson',
  'Snap',
  'Snoop Dogg',
  'Snoop Dogg And Wiz Khalifa Featuring Bruno Mars',
  'Snoop Dogg Featuring Pharrell',
  'Snoop Dogg Featuring Pharrell And Charlie Wilson',
  'Snoop Dogg Featuring R Kelly',
  'Snoop Doggy Dogg',
  'Snow',
  'Snow Patrol',
  'Soft Cell',
  'Somethin For The People Featuring Trina Tamara',
  'Son By Four',
  'Sonique',
  'Sonny Cher',
  'Sonny Bono',
  'Sophie B Hawkins',
  'Soul Asylum',
  'Soul For Real',
  'Soul Ii Soul',
  'Soul Ii Soul Featuring Caron Wheeler',
  'Souldecision Featuring Thrust',
  'Soulja Boy Tell Em',
  'Soulja Boy Tell Em Featuring Sammie',
  'Sounds Orchestral',
  'Spandau Ballet',
  'Spice Girls',
  'Spin Doctors',
  'Spiral Starecase',
  'Stacey Q',
  'Staind',
  'Starbuck',
  'Starland Vocal Band',
  'Starpoint',
  'Stars On 45',
  'Starship',
  'Status Quo',
  'Stealers Wheel',
  'Steely Dan',
  'Stephen Bishop',
  'Steppenwolf',
  'Steve Forbert',
  'Steve Holy',
  'Steve Miller Band',
  'Steve Perry',
  'Steve Winwood',
  'Stevie B',
  'Stevie Nicks',
  'Stevie Nicks Tom Petty',
  'Stevie Nicks And Don Henley',
  'Stevie Wonder',
  'Sting',
  'Sting Featuring Cheb Mami',
  'Stories',
  'Strawberry Alarm Clock',
  'Stray Cats',
  'Styx',
  'Subway Featuring 702',
  'Sugar Ray',
  'Sugarland',
  'Sugarloaf',
  'Sunshine Anderson',
  'Supertramp',
  'Surface',
  'Survivor',
  'Suzanne Vega',
  'Suzi Quatro Chris Norman',
  'Swedish House Mafia Featuring John Martin',
  'Sweet',
  'Sweet Inspirations',
  'Sweet Sensation',
  'Swing Out Sister',
  'Switchfoot',
  'Swv',
  'Swv And Puff Daddy',
  'Sylvia',
  'T Rex',
  'Taco',
  'Tag Team',
  'Taio Cruz',
  'Taio Cruz Featuring Ludacris',
  'Take That',
  'Tal Bachman',
  'Tamia',
  'Tara Kemp',
  'Tatyana Ali',
  'Tavares',
  'Taylor Dayne',
  'Taylor Hicks',
  'Taylor Swift',
  'Taylor Swift Featuring Kendrick Lamar',
  'Tears For Fears',
  'Technotronic Featuring Felly',
  'Technotronic Featuring Ya Kid K',
  'Teddy Geiger',
  'Tee Set',
  'Teena Marie',
  'Terence Trent Darby',
  'Terri Gibbs',
  'Terror Squad',
  'Terry Jacks',
  'Tesla',
  'Tevin Campbell',
  'Thal Ia Featuring Fat Joe',
  'The 5th Dimension',
  'The Ad Libs',
  'The Alan Parsons Project',
  'The Allamerican Rejects',
  'The Allman Brothers Band',
  'The American Breed',
  'The Animals',
  'The Archies',
  'The Association',
  'The B52s',
  'The Babys',
  'The Band Perry',
  'The Bangles',
  'The Beach Boys',
  'The Beatles',
  'The Beatles With Billy Preston',
  'The Beau Brummels',
  'The Bee Gees',
  'The Beginning Of The End',
  'The Bellamy Brothers',
  'The Bells',
  'The Black Eyed Peas',
  'The Blackbyrds',
  'The Blackout Allstars',
  'The Box Tops',
  'The Brotherhood Of Man',
  'The Brothers Johnson',
  'The Buckinghams',
  'The Buoys',
  'The Byrds',
  'The Calling',
  'The Capitols',
  'The Carpenters',
  'The Cars',
  'The Casinos',
  'The Chambers Brothers',
  'The Charlie Daniels Band',
  'The Chilites',
  'The Clash',
  'The Click Five',
  'The Cover Girls',
  'The Cowsills',
  'The Cranberries',
  'The Crazy World Of Arthur Brown',
  'The Cure',
  'The Cyrkle',
  'The Dave Clark Five',
  'The Delfonics',
  'The Dells',
  'The Detroit Emeralds',
  'The Dirt Band',
  'The Doobie Brothers',
  'The Doors',
  'The Dramatics',
  'The Easybeats',
  'The Electric Prunes',
  'The Emotions',
  'The Escape Club',
  'The Esquires',
  'The Fireballs',
  'The First Class',
  'The Floaters',
  'The Flying Machine',
  'The Fortunes',
  'The Foundations',
  'The Four Seasons',
  'The Four Tops',
  'The Fray',
  'The Friends Of Distinction',
  'The Fuzz',
  'The Game Featuring 50 Cent',
  'The Game Featuring Lil Wayne',
  'The Gogos',
  'The Grass Roots',
  'The Greg Kihn Band',
  'The Guess Who',
  'The Guess Who Featuring Wolfman Jack',
  'The Happenings',
  'The Heights',
  'The Hollies',
  'The Hombres',
  'The Honeydrippers',
  'The Hues Corporation',
  'The Human Beinz',
  'The Human League',
  'The Ides Of March',
  'The Intruders',
  'The Irish Rovers',
  'The Isley Brothers',
  'The Isley Brothers Featuring R Kelly And Chante Moore',
  'The J Geils Band',
  'The Jackson 5',
  'The Jacksons',
  'The Jaggerz',
  'The Jeff Healey Band',
  'The Jets',
  'The Killers',
  'The Kingsmen',
  'The Kinks',
  'The Klf',
  'The Knack',
  'The Left Banke',
  'The Lemon Pipers',
  'The Lettermen',
  'The Lovin Spoonful',
  'The Lox Featuring Dmx And Lil Kim',
  'The Lumineers',
  'The Main Ingredient',
  'The Mamas The Papas',
  'The Manhattan Transfer',
  'The Manhattans',
  'The Marshall Tucker Band',
  'The Marvelettes',
  'The Mccoys',
  'The Mills Brothers',
  'The Mindbenders',
  'The Miracles',
  'The Monkees',
  'The Moody Blues',
  'The Motels',
  'The Music Explosion',
  'The Mysterians',
  'The Neighbourhood',
  'The New Seekers',
  'The Notorious Big',
  'The Notorious Big Featuring Puff Daddy And Mase',
  'The Oak Ridge Boys',
  'The Ojays',
  'The Osmonds',
  'The Outfield',
  'The Outsiders',
  'The Partridge Family',
  'The Pipkins',
  'The Pointer Sisters',
  'The Police',
  'The Poppy Family',
  'The Pretenders',
  'The Proclaimers',
  'The Pussycat Dolls Featuring Busta Rhymes',
  'The Rascals',
  'The Red Jumpsuit Apparatus',
  'The Righteous Brothers',
  'The Rolling Stones',
  'The Romantics',
  'The Royal Guardsmen',
  'The Sandpipers',
  'The Script',
  'The Script Featuring William',
  'The Searchers',
  'The Seekers',
  'The Shades Of Blue',
  'The Smashing Pumpkins',
  'The Sos Band',
  'The Soul Survivors',
  'The Spencer Davis Group',
  'The Spinners',
  'The Stampeders',
  'The Standells',
  'The Staple Singers',
  'The Strangeloves',
  'The Stylistics',
  'The Supremes',
  'The Surfaris',
  'The Sylvers',
  'The System',
  'The Temptations',
  'The Three Degrees',
  'The Time',
  'The Tony Rich Project',
  'The Trammps',
  'The Tremeloes',
  'The Troggs',
  'The Tubes',
  'The Turtles',
  'The Undisputed Truth',
  'The Ventures',
  'The Veronicas',
  'The Verve',
  'The Verve Pipe',
  'The Vogues',
  'The Wanted',
  'The Watts 103rd Street Rhythm Band',
  'The Weeknd',
  'The Whispers',
  'The Who',
  'The Winstons',
  'The Yardbirds',
  'The Young Rascals',
  'The Youngbloods',
  'The Zombies',
  'Thelma Houston',
  'Thin Lizzy',
  'Third Eye Blind',
  'Thomas Dolby',
  'Thomas Rhett',
  'Thompson Square',
  'Thompson Twins',
  'Three 6 Mafia',
  'Three 6 Mafia Featuring Young Buck And 8ball Mjg',
  'Three Dog Night',
  'Ti',
  'Ti Featuring Iggy Azalea',
  'Ti Featuring Justin Timberlake',
  'Ti Featuring Rihanna',
  'Tierra',
  'Tiffany',
  'Til Tuesday',
  'Tim Mcgraw',
  'Tim Mcgraw And Faith Hill',
  'Tim Mcgraw Featuring Taylor Swift And Keith Urban',
  'Timbaland Magoo Featuring Missy Elliott And Aaliyah',
  'Timbaland Featuring Drake',
  'Timbaland Featuring Justin Timberlake',
  'Timbaland Featuring Keri Hilson',
  'Timbaland Featuring Nelly Furtado And Justin Timberlake',
  'Timbaland Featuring Onerepublic',
  'Timex Social Club',
  'Timmy T',
  'Timmy Thomas',
  'Tina Turner',
  'Tinashe Featuring Schoolboy Q',
  'Tinie Tempah Featuring Eric Turner',
  'Tlc',
  'Toad The Wet Sprocket',
  'Toby Beau',
  'Toby Keith',
  'Toby Keith Featuring Willie Nelson',
  'Todd Rundgren',
  'Tom Cochrane',
  'Tom Jones',
  'Tom Petty',
  'Tom Petty And The Heartbreakers',
  'Tom T Hall',
  'Tommy James',
  'Tommy James And The Shondells',
  'Tommy Page',
  'Tommy Roe',
  'Tone Loc',
  'Toni Basil',
  'Toni Braxton',
  'Tony Joe White',
  'Tony Orlando And Dawn',
  'Tony Toni Tone',
  'Total',
  'Total Featuring Missy Elliott',
  'Total Featuring The Notorious Big',
  'Toto',
  'Tove Lo',
  'Tower Of Power',
  'Toya',
  'Tpau',
  'Tq',
  'Trace Adkins',
  'Tracey Ullman',
  'Tracie Spencer',
  'Tracy Chapman',
  'Train',
  'Trapt',
  'Travie Mccoy Featuring Bruno Mars',
  'Travis Tritt',
  'Trey Songz',
  'Trey Songz Featuring Fabolous',
  'Trey Songz Featuring Nicki Minaj',
  'Trick Daddy',
  'Trick Daddy Featuring Ludacris Lil Kim And Cee Lo Green',
  'Trillville Featuring Cutty',
  'Truth Hurts Featuring Rakim',
  'Tweet Featuring Missy Elliott',
  'Twista',
  'Twista Featuring Kanye West And Jamie Foxx',
  'Tyga',
  'Tyler Collins',
  'Tyrese',
  'Tyrone Davis',
  'U2',
  'Ub40',
  'Ugly Kid Joe',
  'Uncle Kracker',
  'Uncle Kracker Featuring Dobie Gray',
  'Uncle Sam',
  'Unk',
  'Us3',
  'Usa For Africa',
  'Usher',
  'Usher And Alicia Keys',
  'Usher Featuring Juicy J',
  'Usher Featuring Lil Jon And Ludacris',
  'Usher Featuring Pitbull',
  'Usher Featuring Plies',
  'Usher Featuring William',
  'Usher Featuring Young Jeezy',
  'Van Halen',
  'Van Morrison',
  'Vance Joy',
  'Vanessa Carlton',
  'Vanessa Williams',
  'Vanessa Williams And Brian Mcknight',
  'Vangelis',
  'Vanilla Fudge',
  'Vanilla Ice',
  'Vanity Fare',
  'Various Artists',
  'Vertical Horizon',
  'Vic Dana',
  'Vicki Lawrence',
  'Vicki Sue Robinson',
  'Vikki Carr',
  'Village People',
  'Voices Of Theory',
  'Wadsworth Mansion',
  'Waka Flocka Flame Featuring Wale And Roscoe Dash',
  'Wale Featuring Tiara Thomas',
  'Walk The Moon',
  'Walter Egan',
  'Wang Chung',
  'War',
  'Warrant',
  'Warren G',
  'Warren G Featuring Nate Dogg',
  'Wayne Fontana The Mindbenders',
  'Wayne Newton',
  'Wayne Wonder',
  'We Five',
  'Webbie Featuring Bun B',
  'Webbie Featuring Lil Boosie And Lil Phat',
  'Weezer',
  'Westlife',
  'Wet Willie',
  'Wham',
  'Wham Featuring George Michael',
  'When In Rome',
  'White Lion',
  'White Plains',
  'White Town',
  'Whitesnake',
  'Whitney Houston',
  'Whitney Houston And Mariah Carey',
  'Whitney Houston Featuring Cece Winans',
  'Whitney Houston Featuring Faith Evans And Kelly Price',
  'Wild Cherry',
  'Will Smith',
  'Will Smith Featuring Dru Hill And Kool Moe Dee',
  'Will To Power',
  'Willa Ford',
  'William Devaughn',
  'Willie Nelson',
  'Wilson Phillips',
  'Wilson Pickett',
  'Wing And A Prayer Fife And Drum Corps',
  'Winger',
  'Wings',
  'Wiz Khalifa',
  'Wiz Khalifa Featuring Charlie Puth',
  'Wyclef Jean',
  'Wyclef Jean Featuring Akon Lil Wayne And Niia',
  'X Ambassadors',
  'Xscape',
  'Yes',
  'Yg Featuring Jeezy And Rich Homie Quan',
  'Ying Yang Twins',
  'Ying Yang Twins Featuring Lil Jon The East Side Boyz',
  'Ylvis',
  'Young Dro Featuring Ti',
  'Young Gunz',
  'Young Jeezy Featuring Akon',
  'Young Jeezy Featuring Kanye West',
  'Young Jeezy Featuring R Kelly',
  'Young Mc',
  'Young Money',
  'Young Money Featuring Lloyd',
  'Youngbloodz Featuring Lil Jon',
  'Yung Joc',
  'Yung Joc Featuring Nitti',
  'Yvonne Elliman',
  'Zac Brown Band',
  'Zac Brown Band Featuring Jimmy Buffett',
  'Zager Evans',
  'Zedd Featuring Foxes',
  'Zedd Featuring Hayley Williams',
  'Zhane',
  'Zz Top'
]

export default data
